require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
  
RSpec/LeakyConstantDeclaration:
  Enabled: false
  
Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'